export enum Actions {
  INCREMENT = "INCREMENT",
  DECREMENT = "DECREMENT",
  RESET = "RESET",
  INCREMENT_RANDOM = "INCREMENT_RANDOM",
  INCREMENT_NEAREST_ODD = "INCREMENT_NEAREST_ODD",
  DECREMENT_BY_VALUE = "DECREMENT_BY_VALUE"
}
